#!/bin/sh
set -xeuo pipefail

main() {
    cd "$@"

    export AWS_DEFAULT_REGION=ap-southeast-1 # Make AWS Provider happy

    terraform init -backend=false
    terraform validate
    tflint
}

main "$@"
